name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate with Azure
      uses: azure/login@v2	
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: List Azure subscriptions
      run: az account list --output table
    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt
    - name: attach workspace
      run: az ml folder attach -w "RupeshMLworkspace" -g "aryalrupesh2074-rg"
    - name: retrieve the model
      run: az ml model download -t "." --model-id "roberta-sequence:1"
    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: false
        tags: rupesharyal/roberta:latest
