name: Build and package RoBERTa-sequencing to Dockerhub

on:
  push:
     branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Authenticate with Azure
      uses: azure/login@v2	
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Install Azure ML extension
      run: az extension add --name ml
      
    - name: set auto-install of extensions
      run: az config set extension.use_dynamic_install=yes_without_prompt
      
    - name: Download model from Azure ML
      run: |
        az ml model download \
          --name roberta-sequence \
          --version 1 \
          --workspace-name RupeshMLworkspace \
          --resource-group aryalrupesh2074-rg \
          --download-path .
          
    - name: Authenticate to Docker hub
      uses: docker/login-action@v1
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: build flask-app container
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: rupesharyal/roberta:latest
        

